### ISSUE TITLE
Support HTTPS connection with server

### ISSUE THREAD

**Issue by agilob** [openbmap/android#102]
I'm sure you heard about Let's Encrypt.

**Comment by wish7code** [comment]
Hehe, check out our new website certificate, implemented yesterday.

Sole problem: while desktop browsers (Firefox, IE, Chrome...) work perfectly well with the new certificates, it doesn't work on mobile devices yet: the problem seems to be the missing Let's encrypt intermediate certificate. 

We've got to examine, how this is going on. Unfortunately I fear, that old devices will never receive the missing intermediate certificate :-(

**Comment by agilob** [comment]
I had the same problem and had to support TLS1, 1.1 and 1.2. Otherwise android <=17 couldn't connect.

**Comment by agilob** [comment]
>We've got to examine, how this is going on. Unfortunately I fear, that old devices will never receive the missing intermediate certificate :-(

Probably not, same like windows xp. Thanks!

**Comment by amilopowers** [comment]
My Firefox does connect to the http version by default. Couldn't you add https-everywhere support in your website? Like that security aware folks had https by default and others with older browsers get their insecure http. https://www.eff.org/https-everywhere

On the other hand you could put a rule in your .htaccess file to force everybody to use https. My mobile Firefox handles your certificate with ease. I think it is a matter of time until old browsers (<IE10) loose support and those guys should update ASAP for their security as well.

**Comment by agilob** [comment]
>On the other hand you could put a rule in your .htaccess file to force everybody to use https. My mobile Firefox handles your certificate with ease

Yes, but not every portable device supports LE certificates.

**Comment by AreYouLoco** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

SSL should be requested by default for security.
And then if not supported then HTTP.

It should be quite easy tho. Security important I would say.
-----BEGIN PGP SIGNATURE-----

iQJEBAEBCgAuJxxBcmVZb3VMb2NvPyA8YXJleW91bG9jb0BwYXJhbm9pY2kub3Jn
PgUCVsR9FAAKCRD9y75DgGLNLwZLD/9Z8G6dUJtwUclgSGo0QtyXVgFNNt1OuioZ
cFZYr354MdutxW9gturCqq6wRoDzs9vqLVCtMp5110aA6ognWpZEyU+OUYPaPOGM
1BIHO8fQe629f8DuN6xKA+2nGmL8yiZ5JiXE4PU3UoVRH9cPhOjfQP7hEOIismgx
EWLp4FTdhf+mZLNP+93oAeJoqMlt/Tg+gjOCmbBW+yWeq6eWXaJut5ofmDvLBPtg
ICc9G45h5oEKe2Cx94e+BUST4HtH2bGtaI+zt87wKMb5+g14w89EGbJILCEus0pR
Ytcp1POibuIlE62xf+WzLQRA3NhotEq2rCu0T+rvFKhv8Rb38WoteBIc4vVueU6g
NRvjgINtvzaa9tvezrDwpOFugX7OZ3dcxFBwbH68euz+0yKSNAzt0YoMArw8YnjY
nIO1EEt+WNnWN1h0juGUgrBvx40Yecgnyvg7bo6JrLnjGr/Bd+sTor68dC3EQoJ4
vgQKt8ypEbgXNITev2WJnaUc3tWTLT8A47Dx0Qg598p2aTVBc3e8FoR9xk8+9yDo
9ere3s4GvgbUxZxbi3MlMn4kYGZD75f0yDlxz/U+Rr9npi5ZKRzfRikc75sn/hAX
uB7N+iqIlnpEmrvF9y/FLefOkbbgHbLe4SXYcxYnDkMEN52h9OWBDTIj5DPFiGKR
IZW5+oJc1A==
=oyT3
-----END PGP SIGNATURE-----

**Comment by amilopowers** [comment]
Can we use the https version in Firefox as the location provider?

**Comment by amilopowers** [comment]
It does work with https. https://www.radiocells.org/geolocation/geolocate
So you might want to update the website with the secure URL.

**Comment by wish7code** [comment]
>  Security important I would say.

@AreYouLoco Fully agree for the desktop browser. We don't track visitors browsers but I guess it would be compatible with 99% of visitors anyways..

Nevertheless I also agree on @agilob : If I remember correctly **all ** Android devices below 5.0 aren't supporting LE certificates as the Let's Encrypt root certificate is missing there. So I guess we would lock out still a considerable share of mobile users :-(

> SSL should be requested by default for security. And then if not supported then HTTP.

I'm interested in this: is there an easy way to redirect say a Android 4.4 user if https fails to http only?
https://www.eff.org/https-everywhere is client only, i.e. users would have to install the addon right?

@amilopowers Thanks for testing.. Updated the URL at https://radiocells.org/geolocation#

**Comment by amilopowers** [comment]
Yes you need the Addon to use HTTPS-Everywhere.
