### ISSUE TITLE
Map is deformed

### ISSUE THREAD

**Issue by agilob** [openbmap/android#104]
After the map was downloaded it looks like:

Offline:

![screenshot_2015-12-14-21-42-16](https://cloud.githubusercontent.com/assets/2544251/11794912/cfd9344c-a2ab-11e5-8b5c-7e9f038cc7d2.png)

Online:
![screenshot_2015-12-14-21-45-47](https://cloud.githubusercontent.com/assets/2544251/11794970/14b047ea-a2ac-11e5-8e62-a72db374ec52.png)

Scrolling is really wired, map self-adjusts when I leave map tab and go back to it. Bug present in online and offline map.

**Comment by wish7code** [comment]
Hehe, nice font you got there ;-) Would you mind if I share the screenshot on the mapsforge mailing list?

**Comment by agilob** [comment]
Sure

**Comment by wish7code** [comment]
Posted, see https://groups.google.com/forum/#!topic/mapsforge-dev/3mENgHsTwwA for reference..

**Comment by agilob** [comment]
4.1 with very poor hardware acceleration (it came with 4.0 stock)

**Comment by wish7code** [comment]
Folks at the mapsforge mailing list suggested disabling hardware acceleration.
Let's give it a try..
