### ISSUE TITLE
Split projects into separate repositories

### ISSUE THREAD

**Issue by agilob** [openbmap/android#146]
One repository for tools.
One for RadioBeacon
One for server

Make it easier to contribute and manage code base.

**Comment by wish7code** [comment]
Makes perfect sense ;-)

**Comment by agilob** [comment]
And if possible, please re-create projects as organisation.

**Comment by wish7code** [comment]
First part done, moved tools to a separate repository at https://github.com/wish7code/openbmap_tools

> And if possible, please re-create projects as organisation.

I was wondering, what's the advantage of this?

**Comment by gdt** [comment]
The point of an organization project, as I understand it. is to be able to add multiple people who can all push to it, vs having a single person authorized to push or approve PRs.

**Comment by agilob** [comment]
Also disadvantages pushing directly to master branch skipping code review part.

**Comment by wish7code** [comment]
Thanks guys.. Invited to you to the new team
