### ISSUE TITLE
Wifi captured and uploaded but not shown in the stats or on the map

### ISSUE THREAD

**Issue by merlink01** [openbmap/android#148]
Does it take some time to merge these information on the Server?

Yesterday I uploaded ~ 2000 Wifis, but only Cells are shown in the Stats and no Infos on the Map.

Using Radiobeacon 0.8.15 from Fdroid.

**Comment by wish7code** [comment]
Hey Merlink01!

Sorry for my late reply: indeed it'll take some time till the uploads appear on the map (we're working on near real time map updates, but that'll require still some work..)

But in the meantime your uploads should appear on the map nevertheless.

Please let me know if they don't...

Cheers
Toby
