### ISSUE TITLE
Schedule for Service relaunch?

### ISSUE THREAD

**Issue by letorbi** [openbmap/android#154]
I just want to know when the website and the database will be online again. Is there a roadmap, schedule or anything? I've got 20.000+ Wifis on my Android I want to add ;)

**Comment by wish7code** [comment]
It was just a nightmare: one day before family holydays our server had a SSD failure. Hardware was replaced just in time before leaving, but restoring the software backups from the seaside via VPN failed :-(

I'm just putting everything together again and hope to finish everything over the weekend..
Keep you updated..

**Comment by letorbi** [comment]
Oh my, sorry to hear that. Thx for the update and good luck for the recovery...

**Comment by agilob** [comment]
Hi, how is it going?

**Comment by wish7code** [comment]
Most important things: routing has been fixed, website and files has been restored and re-imported.
Upload service is fine, only the map generation is still a little bit laggy..

If you still see any issues, please let me know..

**Comment by agilob** [comment]
>If you still see any issues, please let me know..

Uploading wardriving sessions fails.

**Comment by wish7code** [comment]
Could you provide me with a logcat?

**Comment by agilob** [comment]
There is no exception, just popup with error "export failed" or something. I'll investigate it later this week.

**Comment by agilob** [comment]
I tried to reproduce it... twice upload worked when I was on logcat, once failed when I was afk.
