### ISSUE TITLE
website: no cells displayed at z14 or higher

### ISSUE THREAD

**Issue by gdt** [openbmap/android#155]
On radiocells.org, cells are displayed z13, but disappear when zooming in.

https://radiocells.org/cell_provider/1067?lat=42.35537263800411&lon=-71.08755111694336&zoom=13

Then zoom in once and they go away.

**Comment by agilob** [comment]
This repo is for android application.

**Comment by gdt** [comment]
It is, but the website repo does not exist, and there are a bunch of other open issues about the website.   I'm happy to use the website repo once it exists.

**Comment by wish7code** [comment]
For me it's ok to use the issue tracker for website issues for the time being.
In the long run I'll plan to release a) the website and b) the geolocation server part to seperate repos. 
Precondition for this is a proper code review though.

To the issue itself, confirmed and under investigation ;-)

**Comment by wish7code** [comment]
Fixed, thanks for reporting!
