### ISSUE TITLE
Export error!

### ISSUE THREAD

**Issue by masyukun** [openbmap/android#164]
**What steps will reproduce the problem?**
I have a long list of sessions to upload, including maybe ~8 already uploaded ones that I'm keeping around to look at at some point. From the main application, I tap and hold the top one until the icon bar appears on the bottom of the screen. I click the upload button.

**What is the expected output? What do you see instead?**
I expect it to take its sweet time uploading thousands of signal. ;) Instead, just the 2 error boxes:

Export error!
Couldn't contact server. Either you're offline or the server is down!

Export error!
Try again later. If problem persists, please file a bug at http://code.google.com/p/openbmap/issues/list

**What version are you using? On what operating system?**
Radiobeacon 0.8.8 (e2a52fc-dirty)
Android 6.0.1 on a Nexus 6
Android security patch level June 1, 2016
Baseband version MDM9625_104662.22.05.34R
Kernel version 3.10.40-geb6cc9d, android-buile@wpef1.hot.corp.google.com

**Please provide any additional information below.**
I enabled USB developer tools, started adb logcat before performing the upload. Here is what I believe to be the relevant section:

06-24 19:08:17.654  3666 14067 I art     : Waiting for a blocking GC DisableMovingGc
06-24 19:08:17.656  3666 14067 I art     : Starting a blocking GC DisableMovingGc
06-24 19:08:18.301 26185 26185 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
06-24 19:08:18.302  2259  3914 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@5d886d7 attribute=null, token = android.os.BinderProxy@4c1adf
06-24 19:08:18.995  3579  3579 I DownloadManagerWrapper: onReceive() : Charging = true
06-24 19:08:19.039 23885 23885 W CycledLeScannerForLollipop: Failed to make new Android L scanner
06-24 19:08:19.635  3579  3579 I DownloadManagerWrapper: onReceive() : Charging = true
06-24 19:08:20.073 23885 23885 W CycledLeScannerForLollipop: Failed to make new Android L scanner
06-24 19:08:20.775  1863  2748 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=4
06-24 19:08:20.832 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:20.832 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.040 23885 23885 W CycledLeScannerForLollipop: Failed to make new Android L scanner
06-24 19:08:23.058 26185 26185 I StartscreenActivity: Refreshing session list fragment
06-24 19:08:23.060  2259  3664 D WifiService: acquireWifiLockLocked: WifiLock{UploadLock type=1 binder=android.os.BinderProxy@c1779cf}
06-24 19:08:23.079  1863  2748 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=4
06-24 19:08:23.101 26185 26185 I StartscreenActivity: Adding 117 to export task list
06-24 19:08:23.105 26185 26185 I StartscreenActivity: Adding 118 to export task list
06-24 19:08:23.110 26185 26185 I StartscreenActivity: Adding 119 to export task list
06-24 19:08:23.113 26185 26185 I StartscreenActivity: Adding 120 to export task list
06-24 19:08:23.118 26185 26185 I StartscreenActivity: Adding 121 to export task list
06-24 19:08:23.122 26185 26185 I StartscreenActivity: Adding 122 to export task list
06-24 19:08:23.126 26185 26185 I StartscreenActivity: Adding 123 to export task list
06-24 19:08:23.130 26185 26185 I StartscreenActivity: Adding 124 to export task list
06-24 19:08:23.135 26185 26185 I StartscreenActivity: Adding 125 to export task list
06-24 19:08:23.193 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.193 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.193 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.193 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.193 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.193 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.194 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.196 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.196 26185 26185 D q       : refreshAdapter skipped. Another update is in progress
06-24 19:08:23.327  2259  2268 I art     : Background partial concurrent mark sweep GC freed 26929(1257KB) AllocSpace objects, 0(0B) LOS objects, 20% free, 62MB/78MB, paused 1.036ms total 107.794ms
06-24 19:08:24.087 23885 23885 W CycledLeScannerForLollipop: Failed to make new Android L scanner
06-24 19:08:24.393 26185 26224 W g       : Http ping failed (return code != 200). Trying to setup connection
06-24 19:08:24.393 26185 26224 I g       : Offline! Device migth just been switched on, so wait a bit
06-24 19:08:24.397 26185 26224 I g       : Current [type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: connected, extra: fast.t-mobile.com, roaming: false, failover: false, isAvailable: true]
06-24 19:08:24.398 26185 26224 I g       : Waited enough: now [type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: connected, extra: fast.t-mobile.com, roaming: false, failover: false, isAvailable: true]
06-24 19:08:24.632  3579  3579 I DownloadManagerWrapper: onReceive() : Charging = true
06-24 19:08:24.734 26185 26224 W g       : Http ping failed (return code != 200). Trying to setup connection
06-24 19:08:24.734 26185 26224 I g       : Waiting didn't help. Still no connection
06-24 19:08:24.736 26185 26185 E g       : Couldn't verify server version. Are you offline?
06-24 19:08:24.737 26185 26185 E StartscreenActivity: Export session 117 failed
06-24 19:08:24.738  2259 16792 D WifiService: releaseWifiLockLocked: WifiLock{UploadLock type=1 binder=android.os.BinderProxy@c1779cf}
06-24 19:08:24.749 26185 26185 E au      : Error exporting session 117: Couldn't contact server. Either you're offline or the server is down!
06-24 19:08:24.750 26185 26185 I au      : Looping over pending exports
06-24 19:08:24.750 26185 26185 I au      : Will process export 118
06-24 19:08:24.763  2259  7472 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@9b3d548 attribute=null, token = android.os.BinderProxy@4c1adf
06-24 19:08:24.763 26185 26228 I k       : Exporting cells
06-24 19:08:24.765 26185 26228 D a       : Start cell export. Data source:  SELECT cells._id, type, is_cdma, is_serving, is_neighbor, cid, actual_cid, utran_rnc, lac, mcc, mnc, psc, baseid, networkid, systemid, OperatorName, Operator, dbm, asu, cells.timestamp, request_pos_id,  "req"."latitude" AS "req_latitude", "req"."longitude" AS "req_longitude", "req"."altitude" AS "req_altitude", "req"."accuracy" AS "req_accuracy", "req"."timestamp" AS "req_timestamp", "req"."bearing" AS "req_bearing", "req"."speed" AS "req_speed",  "last"."latitude" AS "last_latitude", "last"."longitude" AS "last_longitude", "last"."altitude" AS "last_altitude", "last"."accuracy" AS "last_accuracy", "last"."timestamp" AS "last_timestamp", "last"."bearing" AS "last_bearing", "last"."speed" AS "last_speed" FROM cells JOIN "positions" AS "req" ON (request_pos_id = "req"."_id") JOIN "positions" AS "last" ON (last_pos_id = "last"."_id") WHERE cells.session_id = ? ORDER BY request_pos_id LIMIT 3000 OFFSET ?
06-24 19:08:24.775 26185 26228 I b       : Database scheme version 10
06-24 19:08:24.836 26185 26228 I a       : Cycle 0
06-24 19:08:24.893 26185 26228 I a       : Serialize cells took 107 ms
06-24 19:08:24.900 26185 26228 I k       : Exporting wifis
06-24 19:08:24.901 26185 26229 I d       : Uploading /storage/emulated/0/Android/data/org.openbmap/filesV2_310_log20160421124532-cellular.xml
06-24 19:08:24.902 26185 26228 D m       : Start wifi export. Data source:  SELECT wifis._id AS "_id",bssid, ssid, md5ssid, capabilities, frequency, level, wifis.timestamp, request_pos_id AS "request_pos_id",last_pos_id AS "last_pos_id",wifis.session_id, is_known AS "known_wifi", "req"."latitude" AS "req_latitude", "req"."longitude" AS "req_longitude", "req"."altitude" AS "req_altitude", "req"."accuracy" AS "req_accuracy", "req"."timestamp" AS "req_timestamp", "req"."bearing" AS "req_bearing", "req"."speed" AS "req_speed",  "last"."latitude" AS "last_latitude", "last"."longitude" AS "last_longitude", "last"."altitude" AS "last_altitude", "last"."accuracy" AS "last_accuracy", "last"."timestamp" AS "last_timestamp", "last"."bearing" AS "last_bearing", "last"."speed" AS "last_speed" FROM wifis JOIN "positions" AS "req" ON ("request_pos_id" = "req"."_id") JOIN "positions" AS "last" ON ("last_pos_id" = "last"."_id") WHERE wifis.session_id = ? ORDER BY request_pos_id LIMIT 3000 OFFSET ?
06-24 19:08:24.908 26185 26228 I b       : Database scheme version 10
06-24 19:08:25.220 26185 26228 I m       : Cycle 0
06-24 19:08:25.455 26185 26228 I m       : Skipping no ascii ssid rocky's tc
06-24 19:08:25.461 26185 26228 I m       : Skipping no ascii ssid rocky's tc
06-24 19:08:25.477 26185 26228 I m       : Cycle 1000
06-24 19:08:25.565 26185 26228 I m       : Skipping no ascii ssid russ's wi-fi network
06-24 19:08:25.572 26185 26228 I m       : Skipping no ascii ssid russ's wi-fi network
06-24 19:08:25.600 26185 26228 I m       : Skipping no ascii ssid mark's wi-fi network
06-24 19:08:25.721 26185 26228 I m       : Skipping no ascii ssid harley's office
06-24 19:08:25.728 26185 26228 I m       : Skipping no ascii ssid harley's office
06-24 19:08:25.734 26185 26228 I m       : Skipping no ascii ssid harley's office
06-24 19:08:25.735 26185 26228 I m       : Cycle 2000
06-24 19:08:25.743 26185 26228 I m       : Skipping no ascii ssid harley's office
06-24 19:08:25.748 26185 26228 I m       : Skipping no ascii ssid harley's office
06-24 19:08:25.789 26185 26228 I m       : Skipping no ascii ssid jm&a
06-24 19:08:25.792 26185 26228 I m       : Skipping no ascii ssid jm&a
06-24 19:08:25.795 26185 26228 I m       : Skipping no ascii ssid jm&a
06-24 19:08:25.807 26185 26228 I m       : Skipping no ascii ssid djordje's network
06-24 19:08:25.811 26185 26228 I m       : Skipping no ascii ssid djordje's network
06-24 19:08:25.971 26185 26228 I m       : Cycle 3000
06-24 19:08:26.165 26185 26228 I m       : Cycle 0
06-24 19:08:26.389 26185 26229 I d       : Uploaded /storage/emulated/0/Android/data/org.openbmap/filesV2_310_log20160421124532-cellular.xml: Server reply 200
06-24 19:08:26.389 26185 26185 I k       : Finished upload, pending uploads 0
06-24 19:08:26.437 26185 26228 I m       : Cycle 1000
06-24 19:08:26.700 26185 26228 I m       : Serialize wifi took 1782 ms
06-24 19:08:26.704 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:26.704 26185 26224 I d       : Uploading /storage/emulated/0/Android/data/org.openbmap/filesV1_log20160421125859-wifi.xml
06-24 19:08:26.705 26185 26229 I d       : Uploading /storage/emulated/0/Android/data/org.openbmap/filesV1_log20160421133755-wifi.xml
06-24 19:08:26.706 26185 26230 I d       : Uploading /storage/emulated/0/Android/data/org.openbmap/filesV1_log20160421124532-wifi.xml
06-24 19:08:26.715 26185 26231 I d       : Uploading /storage/emulated/0/Android/data/org.openbmap/filesV1_log20160421125502-wifi.xml
06-24 19:08:26.794 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:26.884 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:26.976 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:27.040 23885 23885 W CycledLeScannerForLollipop: Failed to make new Android L scanner
06-24 19:08:27.066 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:27.154 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:27.244 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:27.334 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:27.423 26185 26228 I k       : Waiting for uploads to complete. (Active 6)
06-24 19:08:27.514 26185 26228 I k       : Waiting for uploads to c

**Comment by wish7code** [comment]
Thanks for reporting!

This might be a 0.8.8 specific problem. Do you have the option to upgrade to 0.8.15 (https://f-droid.org/repository/browse/?fdfilter=radiobeacon&fdid=org.openbmap)?

**Comment by agilob** [comment]
Btw. is should be ok to update to 0.8.17 now

**Comment by masyukun** [comment]
Ah, ok. I'll upgrade and check. Hope it doesn't clobber my files, but if so, oh well. 😢

**Comment by masyukun** [comment]
Hey! Looks like it worked! I'll check my stats in a day or so to see if it's loaded in. Thanks!

**Comment by masyukun** [comment]
Yep! All loaded.
