### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by james2432** [openbmap/android#165]
Filled out the form to register and then it fails:

Internal error
Ticket issued: openbmap/173.195.59.34.2016-07-07.19-56-12.a54dc51f-6bb6-44d1-a00e-ffb8583cb267

**Comment by wish7code** [comment]
Thanks for reporting, I'll investigate

**Comment by wish7code** [comment]
Should be solved by now..

In case of problems, please re-open this issue ;-)

Cheers 
Toby

**Comment by james2432** [comment]
there seems to be something wrong with the sign-up I signed up using my email, but when I go to upload it says invalid username/password. I went to the desktop site and tried to recover password, but says invalid username (i'm assuming it's my email as there was no other field to specify a username)

**Comment by wish7code** [comment]
Sorry, messed something up during manual repair..

I fixed it now by setting your username to **james2432** (without the @.. part)
By now you should be able to login/upload using **james2432**

If you prefer another username, let me know via private mail to team@radiocells.org

Hope this helps,
cheers 

Toby

**Comment by james2432** [comment]
Works
