### ISSUE TITLE
[website] every two zoom levels marks on map get misaligned

### ISSUE THREAD

**Issue by agilob** [openbmap/android#168]
See how yellow marks change their position on the map. Depending on zoom level they are where they should, or are moved to left and bottom of the map slightly (looks like they're moved the same ratio of the map on any zoom level. On far zoom-out marks around Cardiff/Bristol are in the sea.

![screenshot_20160818_081609](https://cloud.githubusercontent.com/assets/2544251/17765167/14e46790-651c-11e6-8fdb-131752219866.png)
![screenshot_20160818_081624](https://cloud.githubusercontent.com/assets/2544251/17765168/1500ecbc-651c-11e6-9c05-606229eaf58b.png)

**Comment by wish7code** [comment]
Should be fixed by now.. Feel free to reopen issue if problem persists
