### ISSUE TITLE
radiocells.org offline

### ISSUE THREAD

**Issue by JonnyTech** [openbmap/android#254]
I have a load of scans to upload but radiocells.org is offline, and has been for over a week, so the app cannot reach the server - is there an alternative method to submit my data?

**Comment by JonnyTech** [comment]
I assume that this project is dead. Does an alternative exist?

**Comment by nchristensen** [comment]
OpenCelliD, but it doesn't handle wifi data.

**Comment by JonnyTech** [comment]
Thanks
