### ISSUE TITLE
GPX tracks are no longer exported

### ISSUE THREAD

**Issue by mvglasow** [openbmap/android#91]
Steps to reproduce:
1. Make sure "Save GPX track" option is selected.
2. Start logging.
3. Stop logging and upload.
4. Examine data directory.

Expected output:
I would expect to see the wifi/cell logs (if selected) and the GPX file.

Observed output:
Wifi and cell logs are exported, the GPX file is missing.

Product and OS version:
Radiobeacon 0.8.8 (e2a52fc-dirty) from F-Droid, Cyanogenmot 11 M11 (Android 4.4.4)

Notes:
GPX export worked in versions prior to 0.8.8; looking at my saved files, my last GPX log is from June (around the time I updated to 0.8.8).

**Comment by wish7code** [comment]
Hey Michael,
the gpx files are exported to \Android\data\org.openbmap\files (mind: not \0\Android\data\org.openbmap\files)

Still have to find out, whether this is an actual bug or one of the oddities of the getExternalFilesDir() api...

**Comment by FelixSchwarz** [comment]
For me manually exporting the GPX data never completes (when I don't upload stuff, just export). Maybe that's another symptom of this bug?

**Comment by mvglasow** [comment]
Hi Toby,

what path are you referring to? On my device, radiobeacon-related stuff lives in /storage/emulated/legacy/Android/data/org.openbmap. This is also where the exported cell/wifi files get placed.

Note that my device has two paths that point to its shared storage: /storage/emulated/legacy and /storage/emulated/0. These are the only objects under /storage/emulated (another one, /storage/emulated/usbdisk is added when I plug in a device via USB OTG).

Do you use different API calls for writing the cell/wifi logs and writing GPX?

**Comment by mvglasow** [comment]
Tested 0.8.11 (9fc134d-dirty) for some time. The new option to export GPX manually works, but GPX is still not exported when I upload data. Also, the option for GPX export is gone – hope this is not intentional, as I would like to have an option to export GPX along with all other data in one go.

**Comment by mvglasow** [comment]
Now on 0.8.15 (4b0e71f-dirty), same situation. GPX is not exported automatically, I have to do it manually. A config setting to revert to the old behavior (export GPX automatically) would be very much appreciated.

**Comment by wish7code** [comment]
> hope this is not intentional, 

Was intentional, but with no bad intentions :-) I simply thought nobody would use it..
As this is obviously not the case, we could of course add it again :-)
Just pushed a quickfix (relevant parts in ExportSessionTask.java around L279)..

Find the option under Advanced settings..

**Comment by mvglasow** [comment]
Works in 0.8.18.
